
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mzhKU/config-prop-scc.git
  application:
    name: scc-serverx

debug: false

# Tomcat server
server:
  port: 8888