spring:
  profiles:
    active:
      - default
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/mahed/Documents/repos/test_projects/config-apps
  application:
    name: config-server
server:
  port: 12345